version: "3.7"

x-common:
  &common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  postgresql:
    << : *common
    image: postgres:${LNMP_POSTGRESQL_VERSION:-12.3}-alpine
