version: "3.7"

x-common:
  &common
  restart: always
  env_file: ./cli/timezone.env
  networks:
    - backend
    - frontend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  nginx:
    volumes:
      - laravel_public:/app/laravel-docker/public
      - ./lrew/laravel/config/laravel.conf:/etc/nginx/conf.d/laravel.conf

  laravel:
    << : *common
    image: "${LNMP_BUILD_DOCKER_IMAGE_PREFIX:-khs1994}/laravel:7"
    volumes:
      # fpm config
      - ./config/php/${LNMP_PHP_FPM_CONF:-zz-docker.conf}:/usr/local/etc/php-fpm.d/zz-docker.conf:ro,cached
      # php.ini
      - ./config/php/${LNMP_PHP_INI:-php.development.ini}:/usr/local/etc/php/php.ini:ro,cached
      # php.ini override
      - ./config/php/${LNMP_PHP_EXTRA_INI:-docker-php.ini}:/usr/local/etc/php/conf.d/docker-php.ini:ro,cached
      # log,etc
      - ./log/php:/var/log/php:cached
      - ./lrew/laravel/.env.development:/app/laravel-docker/.env.development
      - laravel_views_cache:/app/laravel-docker/storage/framework/views
      - type: volume
        source: laravel_public
        target: /app/laravel-docker-public-volume
        volume:
          nocopy: true
      - laravel-vscode-server:/root/.vscode-server
      # - laravel-vscode-server-insiders:/root/.vscode-server-insiders
    expose:
      - "9000"
    command: php-fpm -R -F
    environment:
      - APP_ENV=development
      - APP_DEBUG=${APP_DEBUG:-false}
      - LNMP_XDEBUG_REMOTE_HOST=${LNMP_XDEBUG_REMOTE_HOST:-192.168.199.100}
      - LNMP_XDEBUG_REMOTE_PORT=${LNMP_XDEBUG_REMOTE_PORT:-9001}
      - LNMP_OPCACHE_ENABLE=${LNMP_OPCACHE_ENABLE:-1}
    working_dir: /app

volumes:
  laravel_public:
  laravel_views_cache:
  laravel-vscode-server:
  # laravel-vscode-server-insiders:
