workspace:
  base: /data/lnmp
  path: .

pipeline:
  bash:
    image: khs1994/php:7.4.2-composer-alpine
    commands:
      - pwd
      - bash ./lnmp-docker

  # https://hub.docker.com/_/microsoft-powershell?tab=description
  powershell:
    image: mcr.microsoft.com/powershell:alpine-3.8
    commands:
      - pwsh ./lnmp-docker.ps1
