name: containerd
version: 1.3.4
url: "https://github.com/containerd/containerd/releases/download/v${VERSION}/containerd-${VERSION}.linux-amd64.tar.gz"
scripts:
  download: |
    mkdir -force $env:LWPM_PKG_ROOT/dist | out-null

    curl.exe -L `
      $url `
      -o $env:LWPM_PKG_ROOT/dist/$filename
platform:
  - architecture: amd64
    os: linux
