name: runc
version: 1.0.0-rc10
url: "https://github.com/opencontainers/runc/releases/download/v${VERSION}/runc.amd64"
scripts:
  download: |
    _mkdir $env:LWPM_PKG_ROOT/dist | out-null

    curl -L `
      $url `
      -o $env:LWPM_PKG_ROOT/dist/runc
platform:
  - architecture: amd64
    os: linux
