version: "3.7"

services:

  wsl:
    build: .
    image: khs1994/wsl:latest

  wsl-php-builder-72:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_72:-7.2.29}
        - OS_TYPE=debian:buster-slim
    image: khs1994/wsl:khs1994-wsl-php72_${PHP_VERSION_72:-7.2.29}-debian-buster_amd64

  wsl-php-builder-73:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_73:-7.3.16}
        - OS_TYPE=debian:buster-slim
    image: khs1994/wsl:khs1994-wsl-php73_${PHP_VERSION_73:-7.3.16}-debian-buster_amd64

  wsl-php-builder-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.4}
        - OS_TYPE=debian:buster-slim
    image: khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.4}-debian-buster_amd64

  wsl-php-builder-ubuntu1804-72:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_72:-7.2.29}
        - OS_TYPE=ubuntu:18.04
    image: khs1994/wsl:khs1994-wsl-php72_${PHP_VERSION_72:-7.2.29}-ubuntu-bionic_amd64

  wsl-php-builder-ubuntu1804-73:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_73:-7.3.16}
        - OS_TYPE=ubuntu:18.04
    image: khs1994/wsl:khs1994-wsl-php73_${PHP_VERSION_73:-7.3.16}-ubuntu-bionic_amd64

  wsl-php-builder-ubuntu1804-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.4}
        - OS_TYPE=ubuntu:18.04
    image: khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_73:-7.4.4}-ubuntu-bionic_amd64

  wsl-php-builder-rhel7-72:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_72:-7.2.29}
    image: khs1994/wsl:khs1994-wsl-php72_${PHP_VERSION_72:-7.2.29}-centos-7_amd64

  wsl-php-builder-rhel7-73:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_73:-7.3.16}
    image: khs1994/wsl:khs1994-wsl-php73_${PHP_VERSION_73:-7.3.16}-centos-7_amd64

  wsl-php-builder-rhel8-73:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_73:-7.3.16}
        - OS_TYPE=centos:8
    image: khs1994/wsl:khs1994-wsl-php73_${PHP_VERSION_73:-7.3.16}-centos-8_amd64

  wsl-php-builder-rhel8-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.4}
        - OS_TYPE=centos:8
    image: khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.4}-centos-8_amd64

  wsl-php-builder-fc31-73:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_73:-7.3.16}
        - OS_TYPE=fedora:31
    image: khs1994/wsl:khs1994-wsl-php73_${PHP_VERSION_73:-7.3.16}-fedora-31_amd64

  wsl-php-builder-fc31-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.4}
        - OS_TYPE=fedora:31
    image: khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.4}-fedora-31_amd64
