name: conmon
version: 2.0.15
url: "https://github.com/containers/conmon/releases/download/v${VERSION}/conmon"
scripts:
  download: |
    _mkdir $env:LWPM_PKG_ROOT/dist | out-null

    curl -L `
      $url `
      -o $env:LWPM_PKG_ROOT/dist/conmon
platform:
  - architecture: amd64
    os: linux
