version: "3.7"

x-common:
  &common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  mongodb:
    << : *common
    image: mongo:${LNMP_MONGODB_VERSION:-4.2.8}
