name: LREW

on:
  push:
  pull_request:

jobs:
  skip-ci:
    runs-on: ubuntu-latest
    if: |
      (! (contains( github.event.head_commit.message, '[skip ci]')
      || contains( github.event.head_commit.message, '[skip action]')
      || contains( github.event.head_commit.message, '[skip actions]')
      || contains( github.event.head_commit.message, '[ci skip]')
      || contains( github.event.head_commit.message, '[actions skip]')
      || contains( github.event.head_commit.message, '[action skip]')))
    steps:
      - run: echo "build continue !"
  CI:
    runs-on: windows-latest
    needs: skip-ci
    env:
      LNMP_CN_ENV: "false"
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: Set ENV
      run: |
        echo ::add-path::$(pwd)
        echo ::add-path::$(pwd)\windows
        #echo ::set-env name=LNMP_PATH::$(pwd)
    - name: lrew-init
      shell: powershell
      run: lnmp-docker.ps1 lrew-init test
    - name: lrew-init-quite
      shell: powershell
      run: |
        $QUITE=$true
        lnmp-docker.ps1 lrew-init test2
    - name: lrew-add-etcd
      shell: pwsh
      run: |
        lnmp-docker.ps1 lrew-add etcd
    - name: lrew-add-smee
      shell: pwsh
      run: |
        ./lrew/lrew.ps1 add smee
    - name: list vendor
      run: |
        ls -r vendor
