name: lwpm-dist-k8s-file

on:
  push:
    branches:
      - bump-k8s

jobs:
  lwpm-dist-k8s-file:
    name: lwpm-dist-k8s-file
    runs-on: ${{ matrix.os }}-latest
    env:
      LWPM_K8S_VERSION: "1.19.0-alpha.3"

      LWPM_DOCKER_USERNAME: khs1994
      LWPM_DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      LWPM_DIST_ONLY: 'true'
      LWPM_DOCKER_REGISTRY: registry-1.docker.io
    strategy:
      matrix:
        os: ["windows","ubuntu"]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          repository: khs1994-docker/lnmp
          fetch-depth: 1
          path: lnmp
      - name: handle-kubectl
        shell: pwsh
        if: matrix.os == 'windows'
        run: |
          ./lnmp/windows/lnmp-windows-pm.ps1 install kubectl@${env:LWPM_K8S_VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    kubectl@${env:LWPM_K8S_VERSION}
      - name: handle-kubernetes-server
        shell: pwsh
        if: matrix.os == 'windows'
        run: |

          ./lnmp/windows/lnmp-windows-pm.ps1 install kubernetes-server@${env:LWPM_K8S_VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    kubernetes-server@${env:LWPM_K8S_VERSION}
      - name: handle-kubernetes-node
        shell: pwsh
        if: matrix.os == 'ubuntu'
        run: |
          Import-Alias ./lnmp/windows/pwsh-alias.txt -Force

          ./lnmp/windows/lnmp-windows-pm.ps1 install kubernetes-node@${env:LWPM_K8S_VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    kubernetes-node@${env:LWPM_K8S_VERSION}
