name: LWPM

on:
  push:
  pull_request:

jobs:
  skip-ci:
    runs-on: ubuntu-latest
    if: |
      (! (contains( github.event.head_commit.message, '[skip ci]')
      || contains( github.event.head_commit.message, '[skip action]')
      || contains( github.event.head_commit.message, '[skip actions]')
      || contains( github.event.head_commit.message, '[ci skip]')
      || contains( github.event.head_commit.message, '[actions skip]')
      || contains( github.event.head_commit.message, '[action skip]')))
    steps:
      - run: echo "build continue !"
  windows:
    runs-on: windows-latest
    needs: skip-ci
    timeout-minutes: 10
    env:
      LNMP_CN_ENV: false
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 2
    - name: Set ENV
      run: |
        echo ::add-path::$(pwd)\windows
        echo ::add-path::C:\ProgramData\ComposerSetup\bin
        #echo ::set-env name=LNMP_PATH::$(pwd)
    - name: init
      shell: pwsh
      run: echo "extension=openssl" C:\tools\php\php.ini > $null
    - shell: powershell
      run: php -i | select-string .ini
    - run: php -m
    - shell: powershell
      run: cat C:\tools\php\php.ini | select-string extension
    - name: lwpm-install-composer
      shell: powershell
      run: lnmp-windows-pm.ps1 install composer
    - name: lwpm-init-test
      shell: powershell
      run: lnmp-windows-pm.ps1 init test
    - name: lwpm-add-openjdk
      shell: pwsh
      run: lnmp-windows-pm.ps1 add openjdk
    - name: lwpm-install-openjdk
      shell: pwsh
      run: |
        lnmp-windows-pm.ps1 install openjdk
        echo $env:PATH
    - name: lwpm-add-not-exists-pkg
      shell: pwsh
      run: |
        lnmp-windows-pm.ps1 add ooooooo
        echo $env:PATH
    - shell: pwsh
      run: |
        ls -r vendor
